# Generated by Django 4.2.7 on 2025-11-14 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corridor_file', models.FileField(help_text='Corridor definition file (longitude, latitude, altitude, allowed_deviation, allowed_speed)', upload_to='corridors/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('trajectory_file', models.FileField(help_text='Aircraft trajectory file (latitude, longitude, altitude, time)', upload_to='trajectories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('mean_deviation', models.FloatField(blank=True, help_text='Average deviation of trajectory from corridor (in meters)', null=True)),
                ('mean_speed', models.FloatField(blank=True, help_text='Average aircraft speed (km/h)', null=True)),
                ('max_speed', models.FloatField(blank=True, help_text='Maximum aircraft speed (km/h)', null=True)),
                ('corridor_data', models.JSONField(blank=True, help_text='Parsed corridor points', null=True)),
                ('trajectory_data', models.JSONField(blank=True, help_text='Parsed trajectory points with computed speeds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether files have been parsed and analyzed')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
