# Generated by Django 4.2.7 on 2025-11-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcase',
            name='compliance_percentage',
            field=models.FloatField(blank=True, help_text='Percentage of trajectory points within corridor constraints (calculated by C++)', null=True),
        ),
    ]
